'use client';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { ArrowLeft, ArrowRight, CheckCircle2, ChevronDown, CircleHelp, RotateCcw, Shuffle, SkipForward, Sparkles, Trash2, XCircle } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { questions, topicMeta, type Question, type Topic } from '@/lib/content';
import { clearProgress, loadProgress, saveRating, type Mastery, type ProgressState } from '@/lib/progress';
import { MarkdownRenderer } from '@/components/markdown-renderer';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';

function shuffle<T>(items: T[]) { const copy = [...items]; for (let i = copy.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; }
const validTopics = new Set(['all', 'sv', 'uvm', 'axi', 'weak']);

export function PracticeClient() {
  const params = useSearchParams(); const router = useRouter();
  const rawTopic = params.get('topics') || 'all'; const topic = validTopics.has(rawTopic) ? rawTopic : 'all';
  const rawCount = Number(params.get('count') || 10); const count = [10, 20, 50].includes(rawCount) ? rawCount : 10;
  const order = params.get('order') === 'sequential' ? 'sequential' : 'random';
  const [progress, setProgress] = useState<ProgressState>({}); const [session, setSession] = useState<Question[]>([]); const [index, setIndex] = useState(0); const [revealed, setRevealed] = useState(false); const [ready, setReady] = useState(false);
  const buildSession = useCallback((state: ProgressState) => { let pool = topic === 'all' ? questions : topic === 'weak' ? questions.filter((q) => state[q.id]?.mastery === 'fuzzy' || state[q.id]?.mastery === 'unknown') : questions.filter((q) => q.topic === topic); if (order === 'random') pool = shuffle(pool); setSession(pool.slice(0, count)); setIndex(0); setRevealed(false); }, [topic, count, order]);
  useEffect(() => { const state = loadProgress(); setProgress(state); buildSession(state); setReady(true); }, [buildSession]);
  const current = session[index]; const completed = ready && session.length > 0 && index >= session.length;
  const setConfig = (key: string, value: string) => { const next = new URLSearchParams(params.toString()); next.set(key, value); router.replace(`/practice?${next.toString()}`); };
  const next = useCallback(() => { setRevealed(false); setIndex((value) => Math.min(value + 1, session.length)); }, [session.length]);
  const rate = useCallback((mastery: Mastery) => { if (!current) return; setProgress((state) => saveRating(state, current.id, mastery)); next(); }, [current, next]);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement) return; if (event.code === 'Space') { event.preventDefault(); setRevealed(true); } if (revealed && event.key === '1') rate('known'); if (revealed && event.key === '2') rate('fuzzy'); if (revealed && event.key === '3') rate('unknown'); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, [revealed, rate]);
  const topicLabel = topic === 'all' ? '全部主题' : topic === 'weak' ? '薄弱题' : topicMeta[topic as Topic].label;

  return <main className="practice-page shell"><header className="page-heading"><span className="eyebrow"><Sparkles /> 开放问答训练</span><h1>面试刷题</h1><p>先组织自己的回答，再对照知识库中的参考答案。</p></header>
    <section className="practice-toolbar" aria-label="题目设置"><div className="filter-group"><label>主题</label><Select value={topic} onValueChange={(value) => setConfig('topics', value as string)}><SelectTrigger><SelectValue>{topicLabel}</SelectValue></SelectTrigger><SelectContent><SelectItem value="all">全部主题</SelectItem><SelectItem value="sv">SystemVerilog</SelectItem><SelectItem value="uvm">UVM</SelectItem><SelectItem value="axi">AMBA / AXI</SelectItem><SelectItem value="weak">只练薄弱题</SelectItem></SelectContent></Select></div><div className="filter-group"><label>题量</label><Select value={String(count)} onValueChange={(value) => setConfig('count', value as string)}><SelectTrigger><SelectValue>{count} 题</SelectValue></SelectTrigger><SelectContent><SelectItem value="10">10 题</SelectItem><SelectItem value="20">20 题</SelectItem><SelectItem value="50">50 题</SelectItem></SelectContent></Select></div><div className="filter-group"><label>顺序</label><Select value={order} onValueChange={(value) => setConfig('order', value as string)}><SelectTrigger><SelectValue>{order === 'random' ? '随机' : '按章节'}</SelectValue></SelectTrigger><SelectContent><SelectItem value="random">随机</SelectItem><SelectItem value="sequential">按章节</SelectItem></SelectContent></Select></div><Button variant="outline" onClick={() => buildSession(progress)}><Shuffle /> 重新组题</Button><AlertDialog><AlertDialogTrigger render={<Button variant="ghost"><Trash2 /> 清空进度</Button>} /><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>清空全部学习记录？</AlertDialogTitle><AlertDialogDescription>掌握度、练习次数和最近练习时间都会从当前浏览器中删除，此操作无法撤销。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={() => { clearProgress(); setProgress({}); buildSession({}); }}>确认清空</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section>
    {!ready ? <div className="practice-empty">正在准备题目…</div> : session.length === 0 ? <div className="practice-empty"><CircleHelp /><h2>还没有薄弱题</h2><p>先完成一轮普通练习，再回来集中复习“模糊”和“不会”的题目。</p><Link className="primary-cta" href="/practice?topics=all&count=10&order=random">开始随机练习</Link></div> : completed ? <div className="practice-empty"><CheckCircle2 /><h2>本轮练习完成</h2><p>记录已经保存在当前浏览器，可以继续练习薄弱题或重新组题。</p><div className="completion-actions"><Button onClick={() => buildSession(progress)}><RotateCcw /> 再来一轮</Button><Link className="secondary-cta" href="/practice?topics=weak&count=10&order=random">复习薄弱题</Link></div></div> : current && <article className="practice-card"><div className="practice-progress"><div><span>{topicMeta[current.topic].label}</span><strong>{current.section}</strong></div><span>{index + 1} / {session.length}</span></div><Progress value={((index + 1) / session.length) * 100} aria-label={`练习进度 ${index + 1}/${session.length}`} /><div className="question-main"><div className="question-number">Q{String(current.number).padStart(2, '0')}</div><h2>{current.title}</h2>{current.focus.length > 0 && <div className="focus-tags">{current.focus.map((item) => <span key={item}>{item}</span>)}</div>}{!revealed ? <div className="think-state"><p>试着用 1–2 分钟完整表达：先给结论，再解释关键点。</p><Button size="lg" onClick={() => setRevealed(true)}>揭晓参考答案 <ChevronDown /></Button><span>也可以按空格键揭晓</span></div> : <div className="answer-panel"><div className="answer-label">参考答案</div><MarkdownRenderer markdown={current.answer} /><div className="rating"><p>这道题掌握得怎么样？</p><div><Button className="rate-known" variant="outline" onClick={() => rate('known')}><CheckCircle2 /> 掌握 <kbd>1</kbd></Button><Button className="rate-fuzzy" variant="outline" onClick={() => rate('fuzzy')}><CircleHelp /> 模糊 <kbd>2</kbd></Button><Button className="rate-unknown" variant="outline" onClick={() => rate('unknown')}><XCircle /> 不会 <kbd>3</kbd></Button></div></div></div>}</div><footer className="practice-card-foot"><Button variant="ghost" disabled={index === 0} onClick={() => { setIndex((value) => Math.max(0, value - 1)); setRevealed(false); }}><ArrowLeft /> 上一题</Button><Button variant="ghost" onClick={next}>{revealed ? '下一题' : '跳过'} {revealed ? <ArrowRight /> : <SkipForward />}</Button></footer></article>}
  </main>;
}
